### PR TITLE
Add firebase example

### PR DESCRIPTION
**Pull request by jacekschae**
I have a couple of questions to this example :)

It's all working and I also setup a demo site (see README.md)

There is something I was fighting with for a while:

``` clojure
(ns app.fb-auth
  (:require ["firebase" :as firebase :refer [auth]]
            [clojure.string :as string]
            [app.state :as state]))

(defn sign-in-with-google
  []
  (let [fb firebase ;; if we don't bind firebase to fb at this point the next line will not work
        auth (fb.auth.) ;; auth (firebase.auth.) - this would not work and I don't know why?
        provider (fb.auth.GoogleAuthProvider.)] ;; same here (firebase.auth.GoogleAuthProvider.) would not work
    (.catch (.signInWithPopup auth provider)
            (fn [error]
              (throw error)))))
```

Probably I don't understand something, therefore any comments would be helpful.

I also tried to refer auth and do `(auth.)` and `(auth.GoogleAuthProvider.)` but that didn't work either

### CODE REVIEW

**Comment by thheller** [comment]
I'd prefer if this was part of a standalone repo. Keeping multiple examples in a single repo was a bad idea and just makes it harder to use IMHO.

I'm probably going to link all the community examples from the main shadow-cljs README which should make discovery much easier.

Couple other points of feedback though. You should probably avoid using the top-level `"firebase"` require and rather use the independent packages directly.

```clojure
;; instead of
(:require ["firebase" :as fb])
(fb/auth.)

;; do this
(:require ["@firebase/auth" :as fb-auth])
(fb-auth.)
```

When using the top-level `"firebase"` you will always import everything, even parts you might not be using. The `"firebase"` package just seems to delegate to the `@firebase` packages anyways so you are far better off using those directly as it might save you a bunch of bytes later.

 > auth (firebase.auth.) - this would not work and I don't know why?

`firebase` is your `:as` ns alias. as such it must be called with `(firebase/auth.)`.

```clojure
(ns app.fb-auth
  (:require ["firebase" :as firebase]
            [clojure.string :as string]
            [app.state :as state]))

(defn sign-in-with-google
  []
  (let [auth (firebase/auth.)
        provider (firebase/auth.GoogleAuthProvider.)]
    (.catch (.signInWithPopup auth provider)
            (fn [error]
              (throw error)))))
```

**Comment by jacekschae** [comment]
Thanks for your comments and tips. I'll follow your approach and do standalone repo for this one.

After reading a bit more about firebase and how the packages are split it end up being a bit different 

There is one more thing I found at npm repo for firebase and wanted to ask your opinion. In this section - https://www.npmjs.com/package/firebase#api-definition - it says:

> If you use the `Closure Compiler` or compatible IDE, you can find API definitions for all the Firebase JavaScript API in the included /externs directory in this package:

```shell
externs/
  firebase-app-externs.js
  firebase-auth-externs.js
  firebase-database-externs.js
  firebase-storage-externs.js
  firebase-messaging-externs.js
```

After reading the Shadow CLJS User's Guide I believe I can should firebase from there

```clojure
(ns app.fb-db
  (:require ["firebase/externs/firebase-app-externs" :refer [database]]
            [clojure.string :as string]
            [app.state :as state]))
```
and then pass

```clojure
:compiler-options {:infer-externs :auto}
```
or should I rather do this and pass paths to files I'm using?
```clojure
:compiler-options {:externs ["firebase/externs/firebase-app-externs.js" ...]}
```

Thanks

**Comment by jacekschae** [comment]
Thanks for your comments,

BTW. If you use joker to lint there is a fix coming in next release so that it doest'n show an error when you `:require` with string - https://github.com/candid82/joker/issues/48

**Comment by thheller** [comment]
Cool. I don't use joker but some shadow-cljs users do. Note that its an official CLJS feature not just a shadow-cljs thing.

**Comment by thheller** [comment]
I'm collecting a list of shadow-cljs examples to include in the README. I though this was a really neat example. Would you be interested in creating a separate repo for it?

**Comment by jacekschae** [comment]
Sure,

I should do that some time ago already.

Will let you know when it’s there.

Thanks for following up!
Jacek

**Comment by jacekschae** [comment]
@thheller here it is: https://github.com/jacekschae/shadow-firebase

If you would like to amend the description, so that all examples look the same, let me know and I'll happily change that.

**Comment by thheller** [comment]
Excellent. Thanks.

Added both your examples to https://github.com/thheller/shadow-cljs/blob/master/README.md

**Pull request closed without merging**
