### PR TITLE
babel example

### PR DESCRIPTION
**Pull request by alex-dixon**
I switched to babel-preset-env which outputs es5 and it looks like everything is working but reloading is slower. Any idea why?

### CODE REVIEW

**Comment by alex-dixon** [comment]
```
shadow-cljs: WebSocket connected!
browser.cljs:27 shadow-cljs: REPL init successful
=== changed something in cljs ===
browser.cljs:27 shadow-cljs: load JS demo/app.cljs
browser.cljs:27 shadow-cljs: call demo.app/mount-root
=== changed something in js ===
browser.cljs:27 shadow-cljs: load JS node_modules/object-assign/index.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/emptyObject.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/emptyFunction.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/invariant.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/warning.js
browser.cljs:27 shadow-cljs: load JS node_modules/prop-types/lib/ReactPropTypesSecret.js
browser.cljs:27 shadow-cljs: load JS node_modules/prop-types/checkPropTypes.js
browser.cljs:27 shadow-cljs: load JS node_modules/react/cjs/react.development.js
browser.cljs:27 shadow-cljs: load JS node_modules/react/index.js
browser.cljs:27 shadow-cljs: load JS node_modules/create-react-class/factory.js
browser.cljs:27 shadow-cljs: load JS node_modules/create-react-class/index.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/ExecutionEnvironment.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/getActiveElement.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/shallowEqual.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/isNode.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/isTextNode.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/containsNode.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/hyphenate.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/hyphenateStyleName.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/camelize.js
browser.cljs:27 shadow-cljs: load JS node_modules/fbjs/lib/camelizeStyleName.js
browser.cljs:27 shadow-cljs: load JS node_modules/react-dom/cjs/react-dom.development.js
browser.cljs:27 shadow-cljs: load JS node_modules/react-dom/index.js
browser.cljs:27 shadow-cljs: load JS demo/bar.js
browser.cljs:27 shadow-cljs: load JS demo/app.cljs
browser.cljs:27 shadow-cljs: call demo.app/mount-root
```

**Comment by thheller** [comment]
Ah right ... like I said before you need to emit ES6. There is no way around that. For CommonJS the `:shadow` provider is used which is not hot-reloadable.

**Comment by alex-dixon** [comment]
@thheller Ok. Hot reloading appear to work without emitting ES6 it's just slower (seemingly because of walking into node-modules). 

I changed `babel-preset-env` to emit es6 modules. Reloading after changing a JS file is now instant:
```
browser.cljs:27 shadow-cljs: load JS demo/bar.js
browser.cljs:27 shadow-cljs: load JS demo/app.cljs
browser.cljs:27 shadow-cljs: call demo.app/mount-root
```

> I would prefer if you made a standalone repo for this. I kinda regret putting all examples into one repo. I think it is easier to clone and run separate repos.
Sure. Happy to do whatever. I'm not sure I see the advantage of breaking this into 14+ repos though? Having them all in one place made it easy to compare different shadow-cljs features side by side.

If you'd like more documentation for the others I might be able to make a PR for that.

**Comment by thheller** [comment]
I'm more worried about maintenance. Keeping all examples reasonably up-to-date takes a lot of time so I didn't actually do it for most.

**Pull request merged**
